import {Inter} from 'next/font/google';
import './globals.css';

// STATIC COMPONENTS
import Navbar from './components/static/Navbar';
import Footer from './components/static/Footer';
import Header from './components/static/Header';

const inter = Inter({subsets: ['latin']});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({children}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<Navbar />
				<main className="bg-[#000322]">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
